### ISSUE TITLE
IndexError when checking file from stdin

### ISSUE THREAD

**Issue by remcohaszing** [PyCQA/flake8-import-order#81] opened 2016-07-28 07:34 UTC
When linting a file from stdin, this plugin raises an error.

```
$ cat conftest.py | flake8 -
Traceback (most recent call last):
  File "/tmp/venv/bin/flake8", line 11, in <module>
    sys.exit(main())
  File "/tmp/venv/lib/python3.5/site-packages/flake8/main/cli.py", line 16, in main
    app.run(argv)
  File "/tmp/venv/lib/python3.5/site-packages/flake8/main/application.py", line 316, in run
    self._run(argv)
  File "/tmp/venv/lib/python3.5/site-packages/flake8/main/application.py", line 300, in _run
    self.run_checks()
  File "/tmp/venv/lib/python3.5/site-packages/flake8/main/application.py", line 238, in run_checks
    self.file_checker_manager.run()
  File "/tmp/venv/lib/python3.5/site-packages/flake8/checker.py", line 346, in run
    self.run_serial()
  File "/tmp/venv/lib/python3.5/site-packages/flake8/checker.py", line 330, in run_serial
    checker.run_checks(self.results_queue, self.statistics_queue)
  File "/tmp/venv/lib/python3.5/site-packages/flake8/checker.py", line 564, in run_checks
    self.run_ast_checks()
  File "/tmp/venv/lib/python3.5/site-packages/flake8/checker.py", line 475, in run_ast_checks
    for (line_number, offset, text, check) in runner:
  File "/tmp/venv/lib/python3.5/site-packages/flake8_import_order/flake8_linter.py", line 66, in run
    for error in self.check_order():
  File "/tmp/venv/lib/python3.5/site-packages/flake8_import_order/checker.py", line 46, in check_order
    if not pycodestyle.noqa(self.lines[import_.lineno - 1]):
IndexError: list index out of range
```

This does work when just linting a file instead.

```
$ flake8 conftest.py
$
```

I've installed the following packages in my environment (simply a virtualenv using the latest `flake8` and `flake8-import-order`).

```
$ pip list
flake8 (3.0.2)
flake8-import-order (0.9.1)
mccabe (0.5.0)
pip (8.1.2)
pycodestyle (2.0.0)
pyflakes (1.2.3)
setuptools (25.1.0)
wheel (0.29.0)
```

This bug does not yet exist when using the following requirements:

```
flake8 ~= 2.5.5
flake8-import-order ~= 0.8.0
```

I didn't try this using `flake8 ~= 2.6.0`, because this was causing errors related to other plugins.

**Comment by pgjones** [comment] 2016-07-28 21:30
I can reproduce this, but interestingly it depends on using flake8 > 3.0, I'll try and track it down.

**Comment by sigmavirus24** [comment] 2016-07-28 21:33
Ah, so Flake8 3.0 doesn't monkey-patch anyone's stdin. Let me check on something quickly. You can assign this to me if you want @pgjones

**Comment by sigmavirus24** [comment] 2016-07-28 21:42
@remcohaszing can you also confirm that #83 fixes this?

**Comment by pgjones** [comment] 2016-07-30 13:25
Have merged #83, confirmation would be good.

**Comment by remcohaszing** [comment] 2016-07-30 13:28
It works. Thanks :smile:

**Comment by dandavison** [comment] 2017-07-23 13:09
This error does still occur in flake8 2, see https://github.com/PyCQA/flake8-import-order/pull/83/commits/3d3fda825d645a4eb80f3f47c2357dd6ee88c348#r128919106

**Comment by pgjones** [comment] 2017-07-23 20:51
@dandavison I can't reproduce this, could you give me an example of something you think I can reproduce?

**Comment by dandavison** [comment] 2017-07-23 21:06
Sure,

```bash
venv=/tmp/flake8-import-order-venv
virtualenv $venv
. $venv/bin/activate
pip install flake8==2.5.4 flake8-import-order==0.12
cat > bad.py <<EOF
import b
import a
EOF
flake8 - < bad.py
```

```
Traceback (most recent call last):
  File "/tmp/flake8-import-order-venv/bin/flake8", line 11, in <module>
    sys.exit(main())
  File "/tmp/flake8-import-order-venv/lib/python2.7/site-packages/flake8/main.py", line 33, in main
    report = flake8_style.check_files()
  File "/tmp/flake8-import-order-venv/lib/python2.7/site-packages/flake8/engine.py", line 181, in check_files
    return self._retry_serial(self._styleguide.check_files, paths=paths)
  File "/tmp/flake8-import-order-venv/lib/python2.7/site-packages/flake8/engine.py", line 172, in _retry_serial
    return func(*args, **kwargs)
  File "/tmp/flake8-import-order-venv/lib/python2.7/site-packages/pep8.py", line 1842, in check_files
    runner(path)
  File "/tmp/flake8-import-order-venv/lib/python2.7/site-packages/flake8/engine.py", line 126, in input_file
    return fchecker.check_all(expected=expected, line_offset=line_offset)
  File "/tmp/flake8-import-order-venv/lib/python2.7/site-packages/pep8.py", line 1574, in check_all
    self.check_ast()
  File "/tmp/flake8-import-order-venv/lib/python2.7/site-packages/pep8.py", line 1521, in check_ast
    for lineno, offset, text, check in checker.run():
  File "/tmp/flake8-import-order-venv/lib/python2.7/site-packages/flake8_import_order/flake8_linter.py", line 91, in run
    for error in self.check_order():
  File "/tmp/flake8-import-order-venv/lib/python2.7/site-packages/flake8_import_order/checker.py", line 58, in check_order
    if not pycodestyle.noqa(self.lines[import_.lineno - 1]):
IndexError: list index out of range
```

**Comment by sigmavirus24** [comment] 2017-07-24 10:58
So for this to work on Python 2 it must get to [this line](https://github.com/PyCQA/flake8-import-order/blob/a09c1cfeb8e0615c0e1cf92c7798305c815a5200/flake8_import_order/checker.py#L35) which probably gets to [this line](https://github.com/PyCQA/flake8-import-order/blob/a09c1cfeb8e0615c0e1cf92c7798305c815a5200/flake8_import_order/checker.py#L23).

In general, though, this is a new issue given this is against a different version of flake8-import-order and a legacy version of Flake8.

**Comment by pgjones** [comment] 2017-07-24 21:31
@dandavison Can you upgrade to flake8 >=2.6.0 and try again? I can't reproduce the above with any 2.6 patch but I can with 2.5.4.

**Comment by sigmavirus24** [comment] 2017-07-25 11:42
Oh, I suspect that 2.6.0 is when we introduced the monkey-patch to cache `pycodestyle.get_stdin_value`. Alternatively, it's also when we switched our dependency from `pep8` to `pycodestyle`.

**Closed** 2017-07-26 18:11 UTC
