### ISSUE TITLE
Regression in 0.15 with I202 (newline in imports)

### ISSUE THREAD

**Issue by dhermes** [PyCQA/flake8-import-order#122] opened 2017-11-06 21:14 UTC
For a given file `repro.py`, there is a regression:

```
$ virtualenv venv
$ venv/bin/pip install flake8 flake8-import-order numpy
$ venv/bin/python repro.py
Here are my imports:
- matplotlib.pyplot: None
- numpy: <module 'numpy' from '.../venv/lib/python3.6/site-packages/numpy/__init__.py'>
- seaborn: None
- six: <module 'six' from '.../venv/lib/python3.6/site-packages/six.py'>
$
$ venv/bin/pip show flake8-import-order
Name: flake8-import-order
Version: 0.15
$ venv/bin/flake8 repro.py --import-order-style=google
repro.py:10:1: I202 Additional newline in a section of imports.
$
$ venv/bin/pip install 'flake8-import-order==0.14.3'
$ venv/bin/flake8 repro.py --import-order-style=google
$
```

----

```python
# repro.py
try:
    import matplotlib.pyplot as plt
except ImportError:
    plt = None
import numpy as np
try:
    import seaborn  # pylint: disable=unused-import
except ImportError:
    seaborn = None
import six


def main():
    """This is the entry point."""
    print('Here are my imports:')
    print('- matplotlib.pyplot: {}'.format(plt))
    print('- numpy: {}'.format(np))
    print('- seaborn: {}'.format(seaborn))
    print('- six: {}'.format(six))


if __name__ == '__main__':
    main()
```

I don't have any preference for how I do my imports, so I'm happy to change the imports to "conform" to what is expected. Are there equivalent docs? My logic was "keep them in alphabetical order and catch the potential `ImportError`-s as they come".

I have ["fixed"][1] this issue for now in a real code base just by ignoring the error.

[1]: https://github.com/dhermes/bezier/blob/4400e4f300a0b227d7610a3f20d711ea6fe0e0d9/tests/unit/test__algebraic_intersection.py#L21

**Comment by pgjones** [comment] 2017-11-06 21:23
I think this may be due to 
> Correct the flake8 entrypoint to report all I errors, this may result in I2XX errors being reported that were absent previously. 

rather than a regression. 

I this case it is a limitation of this checker that it doesn't pick up the try-except lines (nor the imports within) and hence just sees:
```python
...
import numpy as np



import six
```
and hence it sees an extra line(s). I would write your imports as:
```python
# repro.py
try:
    import matplotlib.pyplot as plt
except ImportError:
    plt = None
try:
    import seaborn  # pylint: disable=unused-import
except ImportError:
    seaborn = None
import numpy as np
import six
```
to work around this. Although I think a `# noqa: I202` is equally sensible.

**Comment by dhermes** [comment] 2017-11-06 21:27
@pgjones Thanks for the quick reply!

1. What about my OCD need for alphabetical imports?
1. Is it correct to conclude that `try/except` are not considered to be imports in any way? Is that bug/"feature request"-worthy?

**Comment by pgjones** [comment] 2017-11-06 21:32
I think the `noqa` is maybe the best I can offer for 1. :), as for 2. I think it could be a feature request but I am unsure how best to implement it - feel free to suggest a PR. I'll close this, as I think we agree this isn't a bug (although reopen if you disagree).

**Closed by pgjones** 2017-11-06 21:32 UTC

**Comment by touilleMan** [comment] 2017-11-15 19:46
Hi,
Got the same trouble with a [group of imports separated by a block of comments](https://github.com/MongoEngine/mongoengine/blob/4d6256e1a166ac434167a734c008caad40529acf/mongoengine/__init__.py#L13)

**Comment by pgjones** [comment] 2017-11-15 22:48
I think the current master branch fixes the block of comments issue, I'll release it soon.
