### ISSUE TITLE
I201 Is Only Enforced When Selected

### ISSUE THREAD

**Issue by pwgraham91** [PyCQA/flake8-import-order#119] opened 2017-11-02 20:05 UTC
flake8 only throws errors on I201 when `--select I201` is used

example:
my_file.py
```
import logging
import wtforms
import wtforms.validators as validators
```
`flake8 my_file.py`
(returns nothing)

`flake8 --select I201 my_file.py`
`my_file.py:4:1: I201 Missing newline before sections or imports. I201 Missing newline before sections or imports.`

**Comment by pgjones** [comment] 2017-11-02 20:31
I think there must be something extra in your setup that explains this, as I can't reproduce this. Is there something in your `setup.cfg` for example?

**Comment by pwgraham91** [comment] 2017-11-02 20:36
I don't have setup.cfg

**Comment by pwgraham91** [comment] 2017-11-02 20:57
I just tried in my /Documents directory with just flake8 and flake8-import-order and got the same result

**Comment by pgjones** [comment] 2017-11-02 22:53
Hmm, do any of [these](http://flake8.pycqa.org/en/latest/user/configuration.html) configuration files exist?

**Comment by pwgraham91** [comment] 2017-11-02 22:58
Unfortunately not

**Comment by pwgraham91** [comment] 2017-11-03 14:00
```
flake8==3.5.0
flake8-import-order==0.14.3
```

**Comment by pgjones** [comment] 2017-11-04 13:08
I can reproduce this if I use Python2, and it seems to be insensitive to the flake8-import-order version, but sensitive to the flake8 version in that it works for flake8 <= 3.3.0. I think it is this [issue](https://gitlab.com/pycqa/flake8/issues/318) that explains the change and the `I10` [here](https://github.com/PyCQA/flake8-import-order/blob/master/setup.py#L55) that causes the bug. Will fix.

**Comment by pgjones** [comment] 2017-11-04 15:13
This should be fixed in master, can you check?

**Comment by pgjones** [comment] 2017-11-05 14:40
Fix confirmed in #121.

**Closed by pgjones** 2017-11-05 14:40 UTC

**Comment by pwgraham91** [comment] 2017-11-06 16:18
verified it works. Thank you!!
